## Numpy_Tutorial

* Impoting numpy as np

In [11]:
import numpy as np

* Create Simple Numpy Array

In [ ]:
arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


* Creating array with range() function

In [ ]:
arr = np.array(range(10))
print(arr)

[0 1 2 3 4 5 6 7 8 9]


* cheack version of numpy



In [ ]:
print(np.__version__)

1.21.6


* Creating numpy array

In [ ]:
arr1 = np.array([1, 2, 3, 4, 5])

print(arr1)


[1 2 3 4 5]


* Type() function

In [ ]:
print(type(arr1))

<class 'numpy.ndarray'>


* array with using tuple

In [ ]:
arr3 = np.array((1, 2, 3, 4, 5))

print(arr3)

[1 2 3 4 5]


### Dimensions in Arrays

* 0-D Arrays

In [ ]:
arr4 = np.array(42)

print(arr4)

42


* 1-D Arrays

In [ ]:
arr5 = np.array([1, 2, 3, 4, 5])

print(arr5)

[1 2 3 4 5]


* 2-D Arrays

In [ ]:
arr6 = np.array([[1, 2, 3], [4, 5, 6]])

print(arr6)

[[1 2 3]
 [4 5 6]]


* 3-D arrays

In [ ]:
arr7 = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr7)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


* Check Number of Dimensions
* arr.ndim used to cheack dimensions 

In [ ]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print("a : ",a.ndim)
print("b : ",b.ndim)
print("c : ",c.ndim)
print("d : ",d.ndim)

a :  0
b :  1
c :  2
d :  3


* **ndmin** is used to define dimensions

In [ ]:
arr8 = np.array([1, 2, 3, 4], ndmin=5)

print(arr8)
print('number of dimensions :', arr8.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


### NumPy Array Indexing

### Access Array Elements

* Get the first element from the following array:

In [ ]:
arr = np.array([1, 2, 3, 4])

print(arr[1])

2


* Get third and fourth elements from the following array and add them.

In [ ]:
print(arr[2] + arr[3])

7


### Access 2-D Arrays

* Access the element on the first row, second column:

In [ ]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('2nd element on 1st row: ', arr[0, 1])

2nd element on 1st row:  2


* Access the element on the 2nd row, 5th column:

In [ ]:
print('5nd element on 2st row: ', arr[1, 4])

print('\nLast element from 2nd dim: ', arr[1, -1])

5nd element on 2st row:  10

Last element from 2nd dim:  10


### Access 3-D Arrays

* Access the third element of the second array of the first array:

In [ ]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[0, 1, 2])

6


### Slicing arrays

* Slice elements from index 1 to index 5 from the following array:

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])

[2 3 4 5]


* Slice elements from index 4 to the end of the array:

In [ ]:
print(arr[4:])

[5 6 7]


* Slice elements from the beginning to index 4 (not included):

In [ ]:
print(arr[:4])

[1 2 3 4]


* Negative Slicing
* Slice from the index 3 from the end to index 1 from the end:

In [ ]:
print(arr[-3:-1])

[5 6]


* step
* Return every other element from index 1 to index 5:

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5:2])

[2 4]


* Return every other element from the entire array:

In [ ]:
print(arr[::2])

[1 3 5 7]


* Slicing 2-D Arrays
* From the second element, slice elements from index 1 to index 4 (not included):

In [ ]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 1:4])

[7 8 9]


* From both elements, return index 2:

In [ ]:
print(arr[0:2, 2])

[3 8]


* From both elements, slice index 1 to index 4 (not included), this will return a 2-D array:

In [ ]:
print(arr[0:2, 1:4])

[[2 3 4]
 [7 8 9]]


### NumPy Data Types

* i - integer
* b - boolean
* u - unsigned integer
* f - float
* c - complex float
* m - timedelta
* M - datetime
* O - object
* S - string
* U - unicode string
* V - fixed chunk of memory for other type ( void )

* Return U - unicode string (<U6)

In [ ]:
arr = np.array(['apple', 'banana', 'cherry'])

print(arr.dtype)

<U6


* Create an array with data type string:

In [ ]:
arr = np.array([1, 2, 3, 4], dtype='S')

print(arr)
print("\n",arr.dtype)

[b'1' b'2' b'3' b'4']

 |S1


* Create an array with data type 4 bytes integer:

In [ ]:
arr = np.array([1, 2, 3, 4], dtype='i4')

print(arr)
print("\n",arr.dtype)

[1 2 3 4]

 int32


* mix value

In [ ]:
arr = np.array(['a', '2', '3'])
print(arr)
arr.dtype

['a' '2' '3']


dtype('<U1')

### The Difference Between Copy and View
* The main difference between a copy and a view of an array is that the copy is a new array, and the view is just a view of the original array.
* The copy owns the data and any changes made to the copy will not affect original array, and any changes made to the original array will not affect the copy.
* The view does not own the data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view.



* Copy()
* Make a copy, change the original array, and display both arrays:

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print("Orignal Array",arr)
print("\nCopy of array",x)


Orignal Array [42  2  3  4  5]

Copy of array [1 2 3 4 5]


* View()
* Make a view, change the original array, and display both arrays:

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


* Make Changes in the VIEW:

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
x[0] = 31

print(arr)
print(x)

[31  2  3  4  5]
[31  2  3  4  5]


* Check if Array Owns its Data
* Every NumPy array has the attribute base that returns None if the array owns the data.

In [ ]:
arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print("Copy : ",x.base)
print("\nView : ",y.base)

Copy :  None

View :  [1 2 3 4 5]


### Shape of an array

* Print the shape of a 2-D array:

In [ ]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)

(2, 4)


* Create an array with 5 dimensions using ndmin

In [ ]:
arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print("\n",arr.ndim)
print('\nshape of array :', arr.shape)

[[[[[1 2 3 4]]]]]

 5

shape of array : (1, 1, 1, 1, 4)


### Reshaping arrays

* Reshape From 1-D to 2-D

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

print(arr,"\n")

newarr = arr.reshape(4, 3)

print(newarr)

[ 1  2  3  4  5  6  7  8  9 10 11 12] 

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


* Reshape From 1-D to 3-D

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

print(arr,"\n")

newarr = arr.reshape(2, 3, 2)

print(newarr)

[ 1  2  3  4  5  6  7  8  9 10 11 12] 

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


* Can We Reshape Into any Shape?
* NO

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(3, 3)

print(newarr)

* Check if the returned array is a copy or a view:

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

print(arr.reshape(2, 4).base)


[1 2 3 4 5 6 7 8]


* -1 is a Unknown Dimension

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(2, 2, -1)

print(newarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


* Flattening the arrays
* Flattening array means converting a multidimensional array into a 1D array.

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

newarr = arr.reshape(-1)

print(newarr)

[1 2 3 4 5 6]


### Iterating Arrays
* Iterating means going through elements one by one.

* As we deal with multi-dimensional arrays in numpy, we can do this using basic for loop of python.

* If we iterate on a 1-D array it will go through each element one by one.

* Iterate on the elements of the following 1-D array:

In [2]:
arr = np.array([1, 2, 3])

for x in arr:
  print(x)

1
2
3


* Iterate on each scalar element of the 2-D array:

In [4]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  for y in x:
    print(y)

1
2
3
4
5
6


* Iterate down to the scalars element of the 3-D array

In [5]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  for y in x:
    for z in y:
      print(z)

1
2
3
4
5
6
7
8
9
10
11
12


### Iterating Arrays Using nditer()
* The function nditer() is a helping function that can be used from very basic to very advanced iterations. It solves some basic issues which we face in iteration, lets go through it with examples.

* Iterating on Each Scalar Element
* In basic for loops, iterating through each scalar of an array we need to use n for loops which can be difficult to write for arrays with very high dimensionality.

* Iterate through the following 3-D array:

In [6]:
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
  print(x)

1
2
3
4
5
6
7
8


### Iterating Array With Different Data Types
* We can use op_dtypes argument and pass it the expected datatype to change the datatype of elements while iterating.

* NumPy does not change the data type of the element in-place (where the element is in array) so it needs some other space to perform this action, that extra space is called buffer, and in order to enable it in nditer() we pass flags=['buffered'].

*Iterate through the array as a string:

In [7]:
arr = np.array([1, 2, 3])

for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
  print(x)

b'1'
b'2'
b'3'


### Iterating With Different Step Size

* Iterate through every scalar element of the 2D array skipping 1 element:

In [8]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for x in np.nditer(arr[:, ::2]):
  print(x)

1
3
5
7


### Enumerated Iteration Using ndenumerate()
* Enumeration means mentioning sequence number of somethings one by one.

* Sometimes we require corresponding index of the element while iterating, the ndenumerate() method can be used for those usecases.

* Enumerate on following 1D arrays elements:

In [9]:
arr = np.array([1, 2, 3])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0,) 1
(1,) 2
(2,) 3


* Enumerate on following 2D array's elements:

In [10]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


### Joining NumPy Arrays
* Joining means putting contents of two or more arrays in a single array.

* In SQL we join tables based on a key, whereas in NumPy we join arrays by axes.

* We pass a sequence of arrays that we want to join to the concatenate() function, along with the axis. If axis is not explicitly passed, it is taken as 0.

In [12]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


* Join two 2-D arrays along rows (axis=1):
* NumPy axes are the directions along the rows and columns

In [13]:
arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)

print(arr)

[[1 2 5 6]
 [3 4 7 8]]


### Joining Arrays Using Stack Functions
* stack() is used for joining multiple NumPy arrays. Unlike, concatenate(), it joins arrays along a new axis.


In [14]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=1)

print(arr)

[[1 4]
 [2 5]
 [3 6]]


* Stacking Along Rows
* NumPy provides a helper function: hstack() to stack along rows.

In [15]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.hstack((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


* Stacking Along Columns
* NumPy provides a helper function: vstack()  to stack along columns.

In [16]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.vstack((arr1, arr2))

print(arr)

[[1 2 3]
 [4 5 6]]


* Stacking Along Height (depth)
* NumPy provides a helper function: dstack() to stack along height, which is the same as depth.

In [17]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.dstack((arr1, arr2))

print(arr)

[[[1 4]
  [2 5]
  [3 6]]]


### Splitting NumPy Arrays
* Splitting is reverse operation of Joining.

* Joining merges multiple arrays into one and Splitting breaks one array into multiple.

* We use array_split() for splitting arrays, we pass it the array we want to split and the number of splits.

* Split the array in 3 parts:

In [18]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


* Split the array in 4 parts:

In [19]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 4)

print(newarr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


* Access the splitted arrays:

In [20]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr[0])
print(newarr[1])
print(newarr[2])

[1 2]
[3 4]
[5 6]


### Splitting 2-D Arrays
* Use the same syntax when splitting 2-D arrays.

* Use the array_split() method, pass in the array you want to split and the number of splits you want to do.

In [21]:
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

newarr = np.array_split(arr, 3)

print(newarr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


* Split the 2-D array into three 2-D arrays.

In [22]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3)

print(newarr)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]


* Split the 2-D array into three 2-D arrays along rows.

In [23]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3, axis=1)

print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


* Use the hsplit() method to split the 2-D array into three 2-D arrays along rows.

In [24]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.hsplit(arr, 3)

print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


* Use the vsplit() method to split the 2-D array into three 2-D arrays along colums.

In [26]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.vsplit(arr, 6)

print(newarr)

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]]), array([[10, 11, 12]]), array([[13, 14, 15]]), array([[16, 17, 18]])]


### Searching Arrays
* You can search an array for a certain value, and return the indexes that get a match.

* To search an array, use the where() method.

* Find the indexes where the value is 4:

In [27]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x)

(array([3, 5, 6]),)


* Find the indexes where the values are even:

In [28]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 0)

print(x)

(array([1, 3, 5, 7]),)


* Find the indexes where the values are odd:

In [30]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 != 0)

print(x)

(array([0, 2, 4, 6]),)


### Search Sorted
* There is a method called searchsorted() which performs a binary search in the array, and returns the index where the specified value would be inserted to maintain the search order.

* The searchsorted() method is assumed to be used on sorted arrays.

* Find the indexes where the value 7 should be inserted:

In [31]:
arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7)

print(x)

1


* Search From the Right Side
* By default the left most index is returned, but we can give side='right' to return the right most index instead.

In [32]:
arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7, side='right')

print(x)

2


* Multiple Values
* To search for more than one value, use an array with the specified values.
* Note: The return value is an array: [1 2 3] containing the three indexes where 2, 4, 6 would be inserted in the original array to maintain the order.



In [33]:
arr = np.array([1, 3, 5, 7])

x = np.searchsorted(arr, [2, 4, 6])

print(x)

[1 2 3]


### Sorting Arrays
* Sorting means putting elements in an ordered sequence.

* Ordered sequence is any sequence that has an order corresponding to elements, like numeric or alphabetical, ascending or descending.

* The NumPy ndarray object has a function called sort(), that will sort a specified array.

In [34]:
arr = np.array([3, 2, 0, 1])

print(np.sort(arr))

[0 1 2 3]


* Sort the array alphabetically:

In [35]:
arr = np.array(['banana', 'cherry', 'apple'])

print(np.sort(arr))

['apple' 'banana' 'cherry']


* Sort a boolean array:

In [36]:
arr = np.array([True, False, True])

print(np.sort(arr))

[False  True  True]


* Sort a 2-D array:

In [37]:
arr = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(arr))

[[2 3 4]
 [0 1 5]]
